# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-25 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanfixContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_contact', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
